/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccountRegistry } from "./AccountRegistry";
export type { Erc20 } from "./Erc20";
export type { Staking } from "./Staking";
export * as factories from "./factories";
export { AccountRegistry__factory } from "./factories/AccountRegistry__factory";
export { Erc20__factory } from "./factories/Erc20__factory";
export { Staking__factory } from "./factories/Staking__factory";
