/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccountRegistry__factory } from "./AccountRegistry__factory";
export { Erc20__factory } from "./Erc20__factory";
export { Staking__factory } from "./Staking__factory";
